services:
  bot:
    container_name: boorubot 
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/db.sqlite:/app/database/db.sqlite
      - ./logs:/app/logs
    command: ["python", "bot.py"]