services:
  boorubot:
    container_name: boorubot 
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/boorubot/database
      - ./logs:/boorubot/logs
    command: ["python", "bot.py"]