version: '3.8'
services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    command: ["python", "bot.py"]